import c from './colours';

export default {
  [c.AZURE_RADIANCE]: [
    'editorInfo.foreground',
    'editorOverviewRuler.infoForeground',
    'inputValidation.infoBackground',
    'inputValidation.infoBorder',
    'terminal.ansiBrightBlue',
  ],
  [c.BRIGHT_GRAY]: [
    'editorIndentGuide.background',
    'editorLineNumber.foreground',
    'editorWhitespace.foreground',
  ],
  [c.BRIGHT_GREEN]: ['terminal.ansiBrightGreen'],
  [c.BUNKER]: [
    'contrastBorder',
    'dropdown.border',
    'editorGroup.border',
    'editorOverviewRuler.border',
    'input.background',
    'panel.border',
    'tab.border',
    'widget.shadow',
  ],
  [c.CADET_BLUE]: [
    'editor.foreground',
    'editorCursor.foreground',
    'peekViewResult.selectionForeground',
    'statusBar.foreground',
    'tab.inactiveForeground',
    'terminal.ansiWhite',
    'terminal.foreground',
    'titleBar.inactiveForeground',
  ],
  [c.CADET_BLUE + '22']: [
    'editor.lineHighlightBackground',
    'editor.selectionHighlightBackground',
    'editorRuler.foreground',
    'editorSuggestWidget.selectedBackground',
    'list.activeSelectionBackground',
    'list.focusBackground',
    'list.inactiveSelectionBackground',
    'peekViewEditor.matchHighlightBackground',
    'peekViewResult.matchHighlightBackground',
    'peekViewResult.selectionBackground',
    'scrollbarSlider.background',
    'tab.hoverBackground',
  ],
  [c.CADET_BLUE + '33']: [
    'editor.selectionBackground',
    'list.hoverBackground',
    'scrollbarSlider.activeBackground',
    'scrollbarSlider.hoverBackground',
  ],
  [c.CINNABAR]: [
    'editorError.foreground',
    'editorOverviewRuler.errorForeground',
    'errorForeground',
    'inputValidation.errorBackground',
    'inputValidation.errorBorder',
    'terminal.ansiBrightRed',
  ],
  [c.CYAN_AQUA]: ['terminal.ansiBrightCyan'],
  [c.ELECTRIC_VIOLET]: ['terminal.ansiBrightMagenta'],
  [c.FOUNTAIN_BLUE]: ['terminal.ansiCyan'],
  [c.HARVEST_GOLD]: [
    'editorOverviewRuler.warningForeground',
    'editorWarning.foreground',
    'inputValidation.warningBackground',
    'inputValidation.warningBorder',
    'terminal.ansiBrightYellow',
  ],
  [c.IRON]: [
    'editor.findMatchHighlightBorder',
    'editorActiveLineNumber.foreground',
    'tab.activeForeground',
    'terminal.ansiBrightWhite',
    'titleBar.activeForeground',
  ],
  [c.JORDY_BLUE]: [
    'editor.findMatchBorder',
    'editor.wordHighlightBorder',
    'editor.wordHighlightStrongBorder',
    'editorBracketMatch.border',
    'editorHoverWidget.border',
    'editorSuggestWidget.border',
    'focusBorder',
    'inputOption.activeBorder',
    'peekView.border',
    'terminal.ansiBlue',
  ],
  [c.LAVENDER]: ['terminal.ansiMagenta'],
  [c.OLIVINE]: ['terminal.ansiGreen'],
  [c.SHARK]: [
    'activityBar.background',
    'editor.background',
    'sideBarSectionHeader.background',
    'statusBar.background',
    'tab.activeBackground',
    'terminal.ansiBlack',
    'titleBar.activeBackground',
    'titleBar.inactiveBackground',
  ],
  [c.SHUTTLE_GRAY]: [
    'editorIndentGuide.activeBackground',
    'terminal.ansiBrightBlack',
  ],
  [c.SUNGLO]: [
    'activityBarBadge.background',
    'button.background',
    'terminal.ansiRed',
  ],
  [c.TRUE_WHITE]: [
    'activityBar.foreground',
    'activityBarBadge.foreground',
    'list.inactiveSelectionForeground',
  ],
  [c.TRANSPARENT]: [
    'editor.findMatchBackground',
    'editor.findMatchHighlightBackground',
    'editor.lineHighlightBorder',
    'editor.wordHighlightBackground',
    'editor.wordHighlightStrongBackground',
  ],
  [c.WHISKEY]: ['terminal.ansiYellow'],
  [c.WOODSMOKE]: [
    'activityBar.dropBackground',
    'editorWidget.background',
    'debugToolBar.background',
    'dropdown.background',
    'editorGroup.background',
    'editorGroupHeader.tabsBackground',
    'editorHoverWidget.background',
    'editorSuggestWidget.background',
    'notificationCenterHeader.background',
    'notifications.background',
    'panel.background',
    'peekViewEditor.background',
    'peekViewResult.background',
    'peekViewTitle.background',
    'sideBar.background',
    'statusBar.debuggingBackground',
    'statusBar.noFolderBackground',
    'statusBarItem.hoverBackground',
    'tab.inactiveBackground',
  ],
};
