import {
  AZURE_RADIANCE,
  BRICK_RED,
  BRIGHT_GRAY,
  BRIGHT_GREEN,
  BUNKER,
  CADET_BLUE,
  CORNFLOWER_BLUE,
  CYAN_AQUA,
  ELECTRIC_VIOLET,
  FOUNTAIN_BLUE,
  HARVEST_GOLD,
  IRON,
  LAVENDER,
  OLIVINE,
  SHARK,
  SHUTTLE_GRAY,
  SUNGLO,
  TRANSPARENT,
  TRUE_WHITE,
  WHISKEY,
  WOODSMOKE,
} from './colours';

export default {
  [AZURE_RADIANCE]: [
    'editorInfo.foreground',
    'editorOverviewRuler.infoForeground',
    'inputValidation.infoBackground',
    'inputValidation.infoBorder',
    'terminal.ansiBrightBlue',
  ],
  [BRICK_RED]: [
    'editorError.foreground',
    'editorOverviewRuler.errorForeground',
    'inputValidation.errorBackground',
    'inputValidation.errorBorder',
    'terminal.ansiBrightRed',
  ],
  [BRIGHT_GRAY]: [
    'editorLineNumber.foreground',
    'list.focusBackground',
    'list.hoverBackground',
  ],
  [BRIGHT_GREEN]: ['terminal.ansiBrightGreen'],
  [BUNKER]: [
    'contrastBorder',
    'dropdown.border',
    'editorGroup.border',
    'editorIndentGuide.background',
    'editorOverviewRuler.border',
    'input.background',
    'panel.border',
    'tab.border',
    'widget.shadow',
  ],
  [CADET_BLUE]: [
    'editor.foreground',
    'editorCursor.foreground',
    'peekViewResult.selectionForeground',
    'statusBar.foreground',
    'tab.inactiveForeground',
    'terminal.ansiWhite',
    'terminal.foreground',
    'titleBar.inactiveForeground',
  ],
  [CADET_BLUE + '22']: [
    'editor.lineHighlightBackground',
    'editor.selectionHighlightBackground',
    'editorIndentGuide.activeBackground',
    'editorRuler.foreground',
    'editorSuggestWidget.selectedBackground',
    'editorWhitespace.foreground',
    'peekViewEditor.matchHighlightBackground',
    'peekViewResult.matchHighlightBackground',
    'peekViewResult.selectionBackground',
    'scrollbarSlider.background',
    'tab.hoverBackground',
  ],
  [CADET_BLUE + '33']: [
    'scrollbarSlider.activeBackground',
    'scrollbarSlider.hoverBackground',
    'editor.selectionBackground',
  ],
  [CORNFLOWER_BLUE]: [
    'editor.findMatchBorder',
    'editor.wordHighlightBorder',
    'editor.wordHighlightStrongBorder',
    'editorBracketMatch.border',
    'editorHoverWidget.border',
    'editorSuggestWidget.border',
    'focusBorder',
    'inputOption.activeBorder',
    'peekView.border',
    'terminal.ansiBlue',
  ],
  [CYAN_AQUA]: ['terminal.ansiBrightCyan'],
  [ELECTRIC_VIOLET]: ['terminal.ansiBrightMagenta'],
  [FOUNTAIN_BLUE]: ['terminal.ansiCyan'],
  [HARVEST_GOLD]: [
    'editorOverviewRuler.warningForeground',
    'editorWarning.foreground',
    'inputValidation.warningBackground',
    'inputValidation.warningBorder',
    'terminal.ansiBrightYellow',
  ],
  [IRON]: [
    'editorActiveLineNumber.foreground',
    'editor.findMatchHighlightBorder',
    'tab.activeForeground',
    'terminal.ansiBrightWhite',
    'titleBar.activeForeground',
  ],
  [LAVENDER]: ['terminal.ansiMagenta'],
  [OLIVINE]: ['terminal.ansiGreen'],
  [SHARK]: [
    'activityBar.background',
    'editor.background',
    'list.activeSelectionBackground',
    'list.inactiveSelectionBackground',
    'sideBarSectionHeader.background',
    'statusBar.background',
    'tab.activeBackground',
    'terminal.ansiBlack',
    'titleBar.activeBackground',
    'titleBar.inactiveBackground',
  ],
  [SHUTTLE_GRAY]: ['terminal.ansiBrightBlack'],
  [SUNGLO]: [
    'activityBarBadge.background',
    'button.background',
    'terminal.ansiRed',
  ],
  [TRUE_WHITE]: ['activityBar.foreground', 'activityBarBadge.foreground'],
  [TRANSPARENT]: [
    'editor.findMatchBackground',
    'editor.findMatchHighlightBackground',
    'editor.lineHighlightBorder',
    'editor.wordHighlightBackground',
    'editor.wordHighlightStrongBackground',
  ],
  [WHISKEY]: ['terminal.ansiYellow'],
  [WOODSMOKE]: [
    'activityBar.dropBackground',
    'editorWidget.background',
    'debugToolBar.background',
    'dropdown.background',
    'editorGroup.background',
    'editorGroupHeader.tabsBackground',
    'editorHoverWidget.background',
    'editorSuggestWidget.background',
    'notificationCenterHeader.background',
    'notifications.background',
    'panel.background',
    'peekViewEditor.background',
    'peekViewResult.background',
    'peekViewTitle.background',
    'sideBar.background',
    'statusBar.debuggingBackground',
    'statusBar.noFolderBackground',
    'statusBarItem.hoverBackground',
    'tab.inactiveBackground',
  ],
};
