const oldPlastic = {
  '#21252b': [
    'activityBar.background',
    'activityBar.dropBackground',
    'editor.background',
    'editorWidget.background',
    'list.activeSelectionBackground',
    'list.inactiveSelectionBackground',
    'peekViewResult.background',
    'peekViewTitle.background',
    'sideBarSectionHeader.background',
    'statusBar.background',
    'statusBar.debuggingBackground',
    'statusBar.noFolderBackground',
    'tab.activeBackground',
    'titleBar.activeBackground',
    'titleBar.inactiveBackground',
  ],
  '#ffffff': ['activityBar.foreground', 'activityBarBadge.foreground'],
  '#e06c75': ['activityBarBadge.background', 'button.background'],
  '#080a0f': [
    'contrastBorder',
    'dropdown.border',
    'editorGroup.border',
    'editorOverviewRuler.border',
    'input.background',
    'panel.border',
    'tab.border',
    'widget.shadow',
  ],
  '#181a1f': [
    'debugToolBar.background',
    'dropdown.background',
    'editorGroup.background',
    'editorGroupHeader.tabsBackground',
    'editorHoverWidget.background',
    'editorSuggestWidget.background',
    'notificationCenterHeader.background',
    'notifications.background',
    'panel.background',
    'peekViewEditor.background',
    'sideBar.background',
    'tab.inactiveBackground',
  ],
  '#42557b': ['editor.findMatchBackground'],
  '#314365': [
    'editor.findMatchHighlightBackground',
    'peekViewEditor.matchHighlightBackground',
    'peekViewResult.matchHighlightBackground',
  ],
  '#abb2bf': [
    'editor.foreground',
    'editorActiveLineNumber.foreground',
    'editorCursor.foreground',
    'peekViewResult.selectionForeground',
  ],
  '#2c313a': [
    'editor.lineHighlightBackground',
    'editorSuggestWidget.selectedBackground',
    'list.focusBackground',
    'peekViewResult.selectionBackground',
    'statusBarItem.hoverBackground',
  ],
  '#3e4451': [
    'editor.selectionBackground',
    'editorIndentGuide.background',
    'editorLineNumber.foreground',
    'editorRuler.foreground',
    'editorWhitespace.foreground',
  ],
  '#00000000': [
    'editor.wordHighlightBackground',
    'editor.wordHighlightStrongBackground',
  ],
  '#61afef': [
    'editor.wordHighlightBorder',
    'editorBracketMatch.border',
    'editorHoverWidget.border',
    'editorSuggestWidget.border',
    'focusBorder',
    'inputOption.activeBorder',
    'peekView.border',
  ],
  '#d2d6db': ['editor.wordHighlightStrongBorder'],
  '#c62d42': [
    'editorError.foreground',
    'editorOverviewRuler.errorForeground',
    'inputValidation.errorBackground',
    'inputValidation.errorBorder',
  ],
  '#1b659d': [
    'editorInfo.foreground',
    'editorOverviewRuler.infoForeground',
    'inputValidation.infoBackground',
    'inputValidation.infoBorder',
  ],
  '#d4ac0d': [
    'editorOverviewRuler.warningForeground',
    'editorWarning.foreground',
    'inputValidation.warningBackground',
    'inputValidation.warningBorder',
  ],
  '#d7dae0': ['list.activeSelectionForeground'],
  '#292d35': ['list.hoverBackground'],
  '#d2d6db77': ['scrollbarSlider.activeBackground'],
  '#3e445177': ['scrollbarSlider.background'],
  '#3e4451aa': ['scrollbarSlider.hoverBackground'],
  '#9da5b4': [
    'statusBar.foreground',
    'tab.activeForeground',
    'titleBar.activeForeground',
  ],
  '#737c8c': ['tab.inactiveForeground'],
  '#6b717d': ['titleBar.inactiveForeground'],
};
