export default {
  WHITE: ['activityBar.foreground', 'activityBarBadge.foreground'],
  TRANSPARENT: [
    'editor.findMatchBackground',
    'editor.findMatchHighlightBackground',
    'editor.lineHighlightBorder',
    'editor.wordHighlightBackground',
    'editor.wordHighlightStrongBackground',
  ],
  foreground: [
    'editor.foreground',
    'editorCursor.foreground',
    'peekViewResult.selectionForeground',
    'statusBar.foreground',
    'tab.inactiveForeground',
    'terminal.foreground',
    'titleBar.inactiveForeground',
  ],
  activeForeground: [
    'editorActiveLineNumber.foreground',
    'editor.findMatchHighlightBorder',
    'list.activeSelectionForeground',
    'tab.activeForeground',
    'titleBar.activeForeground',
  ],
  highlight: [
    'editor.lineHighlightBackground',
    'editorIndentGuide.activeBackground',
    'editorRuler.foreground',
    'editorSuggestWidget.selectedBackground',
    'editorWhitespace.foreground',
    'peekViewEditor.matchHighlightBackground',
    'peekViewResult.matchHighlightBackground',
    'peekViewResult.selectionBackground',
    'scrollbarSlider.background',
    'tab.hoverBackground',
  ],
  activeHighlight: [
    'editor.selectionBackground',
    'editorLineNumber.foreground',
    'scrollbarSlider.activeBackground',
    'scrollbarSlider.hoverBackground',
  ],
  trim: [
    'contrastBorder',
    'dropdown.border',
    'editorGroup.border',
    'editorIndentGuide.background',
    'editorOverviewRuler.border',
    'input.background',
    'panel.border',
    'tab.border',
    'widget.shadow',
  ],
  activeTrim: [
    'activityBarBadge.background',
    'button.background',
    'editor.findMatchBorder',
    'editor.wordHighlightBorder',
    'editor.wordHighlightStrongBorder',
    'editorBracketMatch.border',
    'editorHoverWidget.border',
    'editorSuggestWidget.border',
    'focusBorder',
    'inputOption.activeBorder',
    'peekView.border',
  ],
  main: [
    'activityBar.background',
    'editor.background',
    'list.activeSelectionBackground',
    'list.focusBackground',
    'list.hoverBackground',
    'list.inactiveSelectionBackground',
    'sideBarSectionHeader.background',
    'statusBar.background',
    'tab.activeBackground',
    'titleBar.activeBackground',
    'titleBar.inactiveBackground',
  ],
  panel: [
    'activityBar.dropBackground',
    'debugToolBar.background',
    'dropdown.background',
    'editorGroup.background',
    'editorGroupHeader.tabsBackground',
    'editorHoverWidget.background',
    'editorSuggestWidget.background',
    'editorWidget.background',
    'notificationCenterHeader.background',
    'notifications.background',
    'panel.background',
    'peekViewEditor.background',
    'peekViewResult.background',
    'peekViewTitle.background',
    'sideBar.background',
    'statusBar.debuggingBackground',
    'statusBar.noFolderBackground',
    'statusBarItem.hoverBackground',
    'tab.inactiveBackground',
  ],
  info: [
    'editorInfo.foreground',
    'editorOverviewRuler.infoForeground',
    'inputValidation.infoBackground',
    'inputValidation.infoBorder',
  ],
  warning: [
    'editorOverviewRuler.warningForeground',
    'editorWarning.foreground',
    'inputValidation.warningBackground',
    'inputValidation.warningBorder',
  ],
  error: [
    'editorError.foreground',
    'editorOverviewRuler.errorForeground',
    'inputValidation.errorBackground',
    'inputValidation.errorBorder',
  ],
};
